import LockIcon from "@mui/icons-material/Lock";
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";

const InfoGtown = ({ isAuth }) => {
  let navigate = useNavigate();

  useEffect(() => {
    if (!isAuth) {
      navigate("/login");
    }
  });

  const showTreasuryDasshboard = () => {
    navigate("/treasury-dashboard");
  };

  return (
    <div className="info-outter">
      <div className="infoOneDiv">
        <h1>Gtown treasury</h1>
        <p>
          <strong>Gtown Journal Treasury</strong> or Gtown Treasury, is a
          collected fund generated by selling of authorised gtown journal
          artworks, a portion of the gains are stored in a treasury for all the
          members to access.
        </p>
        <img src={process.env.PUBLIC_URL + "/img/infoImg.png"} alt="info" />
        <p>
          Once a member has received a{" "}
          <strong>Gtown Journal Membership Card</strong>, they can then enter
          the Membership Credentials in the field provided below to access the
          treasury dashboard.
        </p>
        <p>Following is a layout of the Treasury Dashboard.</p>
        <img
          src={process.env.PUBLIC_URL + "/img/treasuryLayout.png"}
          alt="info"
        />
        <p>
          The Treasury Dashboard, provides you with the total community fund
          available and a secured members only chatroom to discuss and allocate
          funds and participate in the mantainance of a smooth cash flow in the
          community.
        </p>
      </div>
      <div className="memberLogin-outter">
        <h1>member id.</h1>
        <div className="cardIcon" onClick={showTreasuryDasshboard}>
          <LockIcon fontSize="large" sx={{ width: "100%" }} />
        </div>
        <input className="memberId" type="password" />
      </div>
    </div>
  );
};

export default InfoGtown;
