import FingerprintIcon from "@mui/icons-material/Fingerprint";
import { useNavigate } from "react-router-dom";
import GtownMap from "./GtownMap";
import { auth, provider } from "../firebase-config";
import { signInWithPopup } from "firebase/auth";
const InfoGtown = ({ setIsAuth }) => {
  let navigate = useNavigate();

  const showTreasuryDasshboard = () => {
    navigate("/treasury-dashboard");
  };

  const signInWithGoogle = () => {
    signInWithPopup(auth, provider).then((result) => {
      localStorage.setItem("isAuth", true);
      localStorage.setItem("userName", result.user.displayName);
      setIsAuth(true);
      navigate("/dashboard");
    });
  };

  return (
    <div className="info-outter">
      <div className="infoOneDiv">
        <div className="treasury-info-main"></div>
        <div className="treasury-head">
          <h1>editorial board</h1>
        </div>
        <div className="info-gtown-map">
          <div>
            <h2>Become an Editor</h2>
            <p>
              Mint your <strong>Gtown Journal Membership Card</strong> today, by
              clicking on the "Mint" button below, every membership comes with a
              unique block of land in the live map.
            </p>
            <button
              className="login-with-google-btn"
              onClick={signInWithGoogle}
            >
              Signin
            </button>
          </div>
          <div>
            <GtownMap />
          </div>
        </div>
        <br />
        <p>
          *40% of every user transaction, goes in the user's treasury dashboard,
          enter your unique membership id below to log in.
        </p>
        <div className="memberLogin-outter">
          <h2>Enter member id to continue.</h2>
          <div className="cardIcon" onClick={showTreasuryDasshboard}>
            <FingerprintIcon fontSize="large" sx={{ width: "100%" }} />
          </div>
          <input className="memberId" type="password" placeholder="Member ID" />
        </div>
        <h3 className="x-x">-------X-------</h3>
        <p>
          <strong>Gtown Journal Treasury</strong> or Gtown Treasury, is a
          collected fund generated by selling of authorised gtown journal
          artworks, a portion of the gains are stored in a treasury for all the
          members to access.
        </p>
        <img src={process.env.PUBLIC_URL + "/img/infoImg.png"} alt="info" />
        <p>
          Once a member has received a{" "}
          <strong>Gtown Journal Membership Card</strong>, they can then enter
          the Membership Credentials in the field provided below to access the
          treasury dashboard.
        </p>
        <p>Following is a layout of the Treasury Dashboard.</p>
        <img
          src={process.env.PUBLIC_URL + "/img/treasuryLayout.png"}
          alt="info"
        />
        <p>
          The Treasury Dashboard, provides you with the total community fund
          available and a secured members only chatroom to discuss and allocate
          funds and participate in the mantainance of a smooth cash flow in the
          community.
        </p>

        <p>
          *Users will automatically be signed out, on refreshing the page or
          clossing the application for security purposes. The application does
          not store userdata.
        </p>
        <h3 className="x-x">-------X-------</h3>
      </div>

      {/* <span className="lastSpan">
        *enter your unique membership id, and press <SavingsRoundedIcon />{" "}
        button to access treasury dashboard.
      </span> */}
    </div>
  );
};

export default InfoGtown;
