import SavingsRoundedIcon from "@mui/icons-material/SavingsRounded";
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import GtownMap from "./GtownMap";

const InfoGtown = ({ isAuth, user }) => {
  let navigate = useNavigate();

  useEffect(() => {
    if (!isAuth) {
      navigate("/login");
    }
  });

  const showTreasuryDasshboard = () => {
    navigate("/treasury-dashboard");
  };

  return (
    <div className="info-outter">
      <div className="infoOneDiv">
        <h1>Gtown treasury</h1>
        <p>
          <strong>Gtown Journal Treasury</strong> or Gtown Treasury, is a
          collected fund generated by selling of authorised gtown journal
          artworks, a portion of the gains are stored in a treasury for all the
          members to access.
        </p>
        <img src={process.env.PUBLIC_URL + "/img/infoImg.png"} alt="info" />
        <p>
          Once a member has received a{" "}
          <strong>Gtown Journal Membership Card</strong>, they can then enter
          the Membership Credentials in the field provided below to access the
          treasury dashboard.
        </p>
        <p>Following is a layout of the Treasury Dashboard.</p>
        <img
          src={process.env.PUBLIC_URL + "/img/treasuryLayout.png"}
          alt="info"
        />
        <p>
          The Treasury Dashboard, provides you with the total community fund
          available and a secured members only chatroom to discuss and allocate
          funds and participate in the mantainance of a smooth cash flow in the
          community.
        </p>
        <div className="info-gtown-map">
          <div>
            <h2>Mint</h2>
            <p>
              Mint your <strong>Gtown Journal Membership Card</strong> today, by
              clicking on the "Mint" button below, every membership comes with a
              unique block of land in the live map.
            </p>
          </div>
          <div>
            <GtownMap />
          </div>
        </div>
        <br />
        <p>
          *20% of every user transaction, goes in the user's treasury dashboard,
          enter your unique membership id below to access your{" "}
          <SavingsRoundedIcon /> Dashboard.
        </p>
        <p>
          *Users will automatically be signed out, on refreshing the page or
          clossing the application for security purposes. The application does
          not store userdata.
        </p>
      </div>
      <div className="memberLogin-outter">
        <h2>{user.displayName}</h2>
        <div className="cardIcon" onClick={showTreasuryDasshboard}>
          <SavingsRoundedIcon fontSize="large" sx={{ width: "100%" }} />
        </div>
        <input className="memberId" type="password" placeholder="Member ID" />
      </div>
      {/* <span className="lastSpan">
        *enter your unique membership id, and press <SavingsRoundedIcon />{" "}
        button to access treasury dashboard.
      </span> */}
    </div>
  );
};

export default InfoGtown;
